#      _____ _ __          _____      __  __  _                 
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                 /____/        
#
# Title of website
title: "PrimeTver"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Разработка бизнес приложений на базе свободного ПО"

# The description is used on homepage and in the footer to quickly describe your website.
description: "Тверской филиал компании ПРАЙМ ГРУП является центром разработки продуктов и прикладных решений на базе свободного ПО."

# Main author of the website
# See > authors.yml
author: primetver

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'http://primetver.ru'
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/primetver/primetver.github.io/edit/master

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'http://primetver.ru/images/'

# Logo size is 600x80 pixels
logo: "logo.png"

# Paginates all X entries
paginate: 5

# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
gems: [jekyll-paginate]
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md

# The language setting is used in /includes/header.html for html-settings
language: "RU-ru"

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
#  ignore:
#    envs: [development]


# Default Settings

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: primetver     # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: primetver     # Default author for posts


#  Open _data/navigation.yml to adjust the left and right topbar navigation


# Verify Website to Webmaster Tools

# google_author:             ""
# google_site_verification:  ""
# bing_webmastertools_id:    ""
# alexa_verify_id:           ""


# Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
# More information » https://mathiasbynens.be/notes/touch-icons

# favicon-32x32:                          "favicon-32x32.png"
# touch-icon-192x192:                     "touch-icon-192x192.png"
# apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
# apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
# apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
# apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
# apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
# apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
# apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
# apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
# msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
# msapplication_tilecolor:                "#fabb00"


# Facebook-Optimization › http://j.mp/fb_optimize

# og_image:                         ""
# og_locale:                        "en_EN"
# og_type:                          "website"
# og_title:                         ""
# og_description:                   ""
# og_url:                           ""
# og_site_name:                     ""


#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#


# Disqus
# used in _includes/comments

# disqus_shortname: 


# SASS
#     More › http://sass-lang.com/
#     More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


# Analytics
#     https://www.google.com/analytics/
# used in _includes/footer_scripts

# google_analytics_tracking_id: 


# Tawk.io
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:
