- menu_name: "Ссылки"

- name: "О компании"
  url: "/info/"
  title: "О Компании"

- name: "Контакты"
  url: "/contact/"
  title: "Контактная информация"

- name: "Служба поддержки"
  url: "https://jira.primetver.ru"
  title: "Регистрация и отслеживание заявок"

- name: "Вакансии"
  url: "/job/"
  title: "Работа а Тверском филиале"

- name: "Лента Atom"
  url: "/atom.xml"
  title: "Подписка на Atom ленту"

- name: "XML карта"
  url: "/sitemap.xml"
  title: "Карта сайта"
